version: "3.8"
services:
  db:
    image: supabase/postgres:15.1.1.46
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
